# Generated by Django 4.1 on 2022-09-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='before_repeat_days',
            field=models.IntegerField(default=0),
        ),
    ]
