# Generated by Django 4.1 on 2022-09-08 23:14

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_card_before_repeat_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.category'),
        ),
    ]
