# Generated by Django 4.1 on 2022-09-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='card',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
